-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d")
FROM REST_REVIEW R1 INNER JOIN 
(SELECT M.MEMBER_ID, MEMBER_NAME, RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING
FROM MEMBER_PROFILE M INNER JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
GROUP BY M.MEMBER_ID
ORDER BY COUNT(*) DESC) AS N1
ON R1.MEMBER_ID = N1.MEMBER_ID
WHERE RANKING = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT;